In [1]:
import pandas as pd

In [3]:
s1 = pd.Series(['a','b','c','d'], name = "old")
s1

0    a
1    b
2    c
3    d
Name: old, dtype: object

In [4]:
s1.dtype

dtype('O')

In [5]:
s2 = pd.Series([1,3,5,8], index = ['a','b','c','d'])
s2

a    1
b    3
c    5
d    8
dtype: int64

In [6]:
s2.values

array([1, 3, 5, 8])

In [8]:
s2['a']

1

In [9]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
s2.values

array([1, 3, 5, 8])

In [11]:
my_dict = {"Google": "Larry",
           "Microsoft": "Bill",
           "Facebook": "Mark",
           "Apple": "Steve"}

In [14]:
s3 = pd.Series(my_dict)
s3

Google       Larry
Microsoft     Bill
Facebook      Mark
Apple        Steve
dtype: object

In [15]:
s3[-1:]

Apple    Steve
dtype: object

In [16]:
s3[-1::-1]

Apple        Steve
Facebook      Mark
Microsoft     Bill
Google       Larry
dtype: object

In [18]:
s3.array

<PandasArray>
['Larry', 'Bill', 'Mark', 'Steve']
Length: 4, dtype: object

In [19]:
s3.index.array

<PandasArray>
['Google', 'Microsoft', 'Facebook', 'Apple']
Length: 4, dtype: object

In [20]:
s3.array

<PandasArray>
['Larry', 'Bill', 'Mark', 'Steve']
Length: 4, dtype: object

In [21]:
s3.index.array

<PandasArray>
['Google', 'Microsoft', 'Facebook', 'Apple']
Length: 4, dtype: object

In [23]:
s6 = pd.period_range('2000',periods = 4)

In [24]:
s6

PeriodIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04'], dtype='period[D]', freq='D')

In [25]:
s7 = [1,2,3,4,5]

In [29]:
s7

[1, 2, 3, 4, 5]

In [34]:
isinstance(s7,list)

True

In [36]:
import numpy as np

In [39]:
s8 = np.asarray(s7)

In [40]:
s8

array([1, 2, 3, 4, 5])

In [41]:
s7

[1, 2, 3, 4, 5]

In [42]:
2*s7

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [48]:
df1 = pd.DataFrame([[1,2,3,4],[5,6,7,8]])
df1

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [50]:
df1[1]

0    2
1    6
Name: 1, dtype: int64

In [52]:
df2 = pd.DataFrame([[1,   2,   3,    7],  # ignore the weird spacing, it's just to be clear we have 3 lists of 4 
                    [4.2, 6.1, 8.9, -4.1], 
                    ["a", "b", "c", "z"] ])
df2

0    1    2    3
0    1    2    3    7
1  4.2  6.1  8.9 -4.1
2    a    b    c    z

In [54]:
df2[0]

0      1
1    4.2
2      a
Name: 0, dtype: object

In [60]:
s1 = ['sonia','javad','omid']
s2=['seyed allaei','hatami1','hatami2']
s1_ser = pd.Series(s1)
s2_ser = pd.Series(s2)

In [62]:
s2_ser

0    seyed allaei
1         hatami1
2         hatami2
dtype: object

In [63]:
s3 = df2 = pd.DataFrame([[1,   2,   3,    7],  # ignore the weird spacing, it's just to be clear we have 3 lists of 4 
                    [4.2, 6.1, 8.9, -4.1], 
                    ["a", "b", "c", "z"] ])

In [65]:
s3 = pd.DataFrame({'Name':s1_ser,'family':s2_ser})

In [66]:
s3

Name        family
0  sonia  seyed allaei
1  javad       hatami1
2   omid       hatami2

In [76]:
s3["age"] = [39,38,4]

In [77]:
s3

Name        family  age       city
0  sonia  seyed allaei   39     Tehran
1  javad       hatami1   38  Esfarayen
2   omid       hatami2    4     Aveiro

In [78]:
s3['city'] =['Tehran','Esfarayen','Aveiro']

In [79]:
s3

Name        family  age       city
0  sonia  seyed allaei   39     Tehran
1  javad       hatami1   38  Esfarayen
2   omid       hatami2    4     Aveiro

In [73]:
for col in s3.columns:
    print(col)

Name
family
age
city


In [80]:
s3.dtypes

Name      object
family    object
age        int64
city      object
dtype: object

In [81]:
s4 = s3.to_numpy()

In [82]:
s4

array([['sonia', 'seyed allaei', 39, 'Tehran'],
       ['javad', 'hatami1', 38, 'Esfarayen'],
       ['omid', 'hatami2', 4, 'Aveiro']], dtype=object)

In [85]:
s4[1][0]

'javad'

In [86]:
s3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   family  3 non-null      object
 2   age     3 non-null      int64 
 3   city    3 non-null      object
dtypes: int64(1), object(3)
memory usage: 224.0+ bytes


In [87]:
data = pd.read_csv("data/2010_Census_Populations_by_Zip_Code.csv")

In [88]:
data

Zip Code  Total Population  Median Age  Total Males  Total Females  \
0       91371                 1        73.5            0              1   
1       90001             57110        26.6        28468          28642   
2       90002             51223        25.5        24876          26347   
3       90003             66266        26.3        32631          33635   
4       90004             62180        34.8        31302          30878   
..        ...               ...         ...          ...            ...   
314     93552             38158        28.4        18711          19447   
315     93553              2138        43.3         1121           1017   
316     93560             18910        32.4         9491           9419   
317     93563               388        44.5          263            125   
318     93591              7285        30.9         3653           3632   

     Total Households  Average Household Size  
0                   1                    1.00  
1               12971                    4.40  
2               11731                    4.36  
3               15642                    4.22  
4               22547                    2.73  
..                ...                     ...  
314              9690                    3.93  
315               816                    2.62  
316              6469                    2.92  
317               103                    2.53  
318              1982                    3.67  

[319 rows x 7 columns]

In [101]:
data.head(n=5)

Zip Code  Total Population  Median Age  Total Males  Total Females  \
0     91371                 1        73.5            0              1   
1     90001             57110        26.6        28468          28642   
2     90002             51223        25.5        24876          26347   
3     90003             66266        26.3        32631          33635   
4     90004             62180        34.8        31302          30878   

   Total Households  Average Household Size  
0                 1                    1.00  
1             12971                    4.40  
2             11731                    4.36  
3             15642                    4.22  
4             22547                    2.73

In [102]:
ds = data.to_numpy()

In [108]:
data.describe()

Zip Code  Total Population  Median Age   Total Males  \
count    319.000000        319.000000  319.000000    319.000000   
mean   91000.673981      33241.341693   36.527586  16391.564263   
std      908.360203      21644.417455    8.692999  10747.495566   
min    90001.000000          0.000000    0.000000      0.000000   
25%    90243.500000      19318.500000   32.400000   9763.500000   
50%    90807.000000      31481.000000   37.100000  15283.000000   
75%    91417.000000      44978.000000   41.000000  22219.500000   
max    93591.000000     105549.000000   74.000000  52794.000000   

       Total Females  Total Households  Average Household Size  
count     319.000000        319.000000              319.000000  
mean    16849.777429      10964.570533                2.828119  
std     10934.986468       6270.646400                0.835658  
min         0.000000          0.000000                0.000000  
25%      9633.500000       6765.500000                2.435000  
50%     16202.000000      10968.000000                2.830000  
75%     22690.500000      14889.500000                3.320000  
max     53185.000000      31087.000000                4.670000