In [2]:
import numpy as np
aa = np.array([1,2,3,4,5])
aa

array([1, 2, 3, 4, 5])

In [4]:

>>> p = np.append( [1], aa)

In [5]:
p

array([1, 1, 2, 3, 4, 5])

In [6]:
x = np.array([1,2,3,4,5,6])

In [7]:
np.matmul(x,p)

71

In [10]:
pp = np.array([1,2,3,4,5,6]).reshape((2,3))

In [11]:
pp

array([[1, 2, 3],
       [4, 5, 6]])