In [1]:
import numpy as np
import pandas as pd

In [4]:
a = np.array(range(0,40)).reshape(5,8)

In [5]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [26]:
ac = np.concatenate((np.ones(a.shape[0]).reshape(1,-1).T,a),axis = 1)
ac


array([[ 1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 1.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 1., 16., 17., 18., 19., 20., 21., 22., 23.],
       [ 1., 24., 25., 26., 27., 28., 29., 30., 31.],
       [ 1., 32., 33., 34., 35., 36., 37., 38., 39.]])

In [19]:
np.insert(np.ones(a.shape[0]),a,axis=1)

TypeError: _insert_dispatcher() missing 1 required positional argument: 'values'

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [34]:
y = np.array(range(0,6)).reshape(1,-1)
y

array([[0, 1, 2, 3, 4, 5]])

In [30]:
yhat = np.array(range(10,16))
yhat

array([10, 11, 12, 13, 14, 15])

In [31]:
y-yhat

array([-10, -10, -10, -10, -10, -10])