In [1]:
import pandas as pd
import numpy as np


In [2]:
df_salary = pd.read_csv('data/salary_data.csv')
df_salary.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [3]:
q = np.array([1,2,3,4])

In [4]:
3*q

array([ 3,  6,  9, 12])

In [5]:
2*np.ones(3)

array([2., 2., 2.])

In [6]:
len(np.array([1,2,3,4]))

4

In [36]:
# Base imports
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import hashlib

np.random.seed(42)

In [39]:
betas = np.array([1,2,3,4,5,6])
betas

array([1, 2, 3, 4, 5, 6])

In [41]:
betas = betas.reshape((1, -1))
betas.shape

(1, 6)

In [42]:
x = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
# Extend the matrix x with a collumn of ones
    # X_mat = ...
    # YOUR CODE HERE
    s = x.shape[0]
    s

    #raise NotImplementedError()

2

In [57]:
x.shape

(2, 5)

In [56]:
np.transpose( np.ones(s).reshape(1,-1)).shape

(2, 1)

In [60]:
X_mat = np.concatenate(( np.transpose(np.ones(s).reshape(1,-1)),x), axis = 1)

In [61]:
X_mat

array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 1.,  6.,  7.,  8.,  9., 10.]])