In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
a2 = a**2
a2

array([ 1,  4,  9, 16])

In [8]:
a2.sum()

30

In [9]:
y = np.array([1,2,3,4,5])

In [10]:
y.shape

(5,)

In [12]:
y = y.reshape(1,-1)

In [13]:
y

array([[1, 2, 3, 4, 5]])

In [14]:
y.shape

(1, 5)

In [16]:
yy = y**2

In [17]:
yy.sum()

55